### ISSUE TITLE
Crashes when trying to run map dota.bsp

### ISSUE THREAD

**Issue by leinfink** [ash47/Frota#174]
I changed "map riverofsouls.bsp" to "map dota.bsp" and he seemed to load it without problems, but then scrds.exe crashed without any error messages. Dota 2 could not load the map.

**Comment by enchantinggg4** [comment]
Hey, sorry for digging up this dead issue - but perhaps you've got referenced map archived?  Or any recipe to make default dota map launchable?
And yes, I'm well aware that this is source 1 dota 2 addon from 11 years ago @ash47

**Comment by ash47** [comment]
Hi,

I can probably dig this file up if required.

If you help me understand what you want to do then I might be able to give
you something more useful.

For my newest custom game nice mode, "Legends of Dota", I made the default
map available by using the workshop tools, opening hammer, opening the copy
of the default map that ships with the SDK, savings it with a new file name
in my add-on, building it and then I think adding it to the map list.

If that doesn't help, please let me know your use case and I can either
better direct you or share the file you requested.

 - Ash47

**Comment by y0nkers** [comment]
Hi there!

The author of the previous message went fishing on the great lake Baikal, so he asked me to answer.

We are trying to make a turbo mode with the default map on patch 6.84 (Source 1) via an addon. When trying to run the addon on the default map, the server crashes. The addon is planned to be a server side, the client should not download the map.

P.S. Small maps like the default tutorial or flatgrass from Z-Machine (https://github.com/Z-Machine/Flatgrass) work and do not crash the server.

**Comment by ash47** [comment]
[dota_lod.zip](https://github.com/user-attachments/files/21825174/dota_lod.zip)

As requested, here is the file that was referenced, I pulled out the version that was commited / there at the time of that post, from 2014. Not sure if you can just rename it to dota.bsp or not, i think this may have been a map I compiled, but not really sure. Let me know if it helps.

**Comment by enchantinggg4** [comment]
Hello again! this map indeed fixed the problem we had, but its from older patch that we use.
If i understand correctly, what you did for this map is just:
1) open default map in hammer
2) rebuild it
or perhaps there are more steps?

**Comment by enchantinggg4** [comment]
For clarification and perhaps you've got this map already: we use 6.84c patch, which has highgrounds in fountain areas and moved roshan pit from original(at the time) near dire middle t1 to river near bottom rune.

**Comment by ash47** [comment]
Hi,

I don't have that specific file.

It may be possible to just install the version of Dota 2 that you're
looking for.

From Reddit: Guide: How to download older versions of a game on Steam

https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/

Not sure if they have the full history of every version of Dota 2 still,
but they might.

Best of luck :) 🤞

**Comment by enchantinggg4** [comment]
Yes, we already have the original map and the game client!
But if we try to run original maps, as I said, server crashes, but with dota_lod you provided - it doesn't. 
I just want to clarify how exactly you made dota_lod map - so we can repeat the process with the map we need to launch.

We tried to build 6.84 map using alien swarm SDK hammer, but it fails with "512 overlay limit" error, so we're stuck currently, so if you can recall the process of "fixing" original map it would be very cool!

**Comment by y0nkers** [comment]
Hi, small update:

We managed to get around the "Too many overlays" error during recompilation by temporarily deleting all info_overlay entities on map. 

We also reduced the map bounds by reducing the size of the yellow spheres and tall rectangles (we are noobs in hammer and don't know which of these are actually bounds, so we tried both). The server still crashes when a client connects =(

**Comment by enchantinggg4** [comment]
> I've looked into this A LOT and I found out that it's crashing because dota's bounds are too high -- I can fix it by lowering the map boundaries, however it would mean shipping an 18MB map >_>

I'm pretty sure we need an algorithm to "lower map boundaries". As y0nkers said, we are pretty noob and most tools are outdated for our case as well as documentation, so any help is gigantic. As we said, we only need to get original map to running.

**Comment by ash47** [comment]
Have you guys tried just renaming it to dota_lod.bsp (the updated map), and
seeing if it works? There is no hammer for Dota 2 source 1, I just searched
it up, so it seems unlikely I would have rebuilt the map with hammer for
this -- it's something I did for source 2 version and must have gotten
mixed up.

Frota was from the d2ware days, if you want to run a server, you probably
need to use metamod and do some config stuff, there's a bunch of info in
the readme about it.

There's specifically references to this mod which fixed crashes:

https://forums.alliedmods.net/archive/index.php/t-209965.html

**Comment by enchantinggg4** [comment]
We already have metamod and sourcemod, as well as d2fixups
We can run basic dedicated server with stuff above, but we want to incorporate lua scripting as well, so that's why we try hosting it as an addon.
We tried following this guide - https://app.readthedocs.org/projects/d2moddin/downloads/pdf/latest/
And it says 

> You cannot decompile and re-compile the dota.bsp map as it has too many overlays. The overlay limit was raised to
8192 from 512 for Dota 2, but the compiler toolchain still works under the 512 limit.
But somehow dota_lod works! even though its just a basic dota map. 

Renaming map doesn't help. If there was no hammer for source 1 dota, how were maps for custom games created? like river of souls and etc

**Comment by ash47** [comment]
@enchantinggg4 Share the file here (dota.bsp), the broken one, I might be able to repair it with a private tool.

**Comment by enchantinggg4** [comment]
[dota.zip](https://github.com/user-attachments/files/21956484/dota.zip)

Here is original map

**Comment by ash47** [comment]
[dota_fixed.zip](https://github.com/user-attachments/files/21956508/dota_fixed.zip)

I don't have an old version of the game to test with, but here is an attempt at fixing the issue with a private tool, let me know if that helps, or if it still just crashes,

**Comment by enchantinggg4** [comment]
Unfortunately, this didn’t help with server crashing 

![Image](https://github.com/user-attachments/assets/99646a15-255b-4cac-bbd0-a0aa983eb6f5)

Also, it now spams this inline model error on client when connecting

**Comment by enchantinggg4** [comment]
Just to reiterate: launching original map without addon is fine. Issue only appears if srcds runs an addon

**Comment by ash47** [comment]
Crashes at exactly what point and under what conditions? What does the
crash / console log say at the time of crash?

**Comment by y0nkers** [comment]
The server crashes a few seconds after a client tries to connect to it.

Here are the logs from the server and from the client console for two situations - when the server crashes (dota_fixed map) and when it doesn't crash (dota_lod map)

[logs.zip](https://github.com/user-attachments/files/21957196/logs.zip)
